version: '3.1'
services:
  book:
    image: powerfulyang/book.powerfulyang.com
    build:
      context: .
    container_name: book
    command: gitbook serve
    ports:
      - 5000:4000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
